### ISSUE TITLE
Convert JSON back to BibTeX

### ISSUE THREAD

**Issue by jrsmith3** [mattmight/bib2sx#6]
It looks like this tool can convert BibTeX to JSON, but it would be great if it could convert that JSON back to BibTeX.

**Comment by mattmight** [comment]
Yes, it can convert BibTeX to JSON, and it would be useful to be able to go JSON to BiBTeX.

A good way to do that would be to write a separate tool in node.js, since it can parse the JSON natively there, in the same way that Racket can parse S-Expressions natively here.

So, I'm not likely to implement that as a feature in this tool, but `json2bib` could be its own standalone tool.
